### PR TITLE
new user guide document

### PR DESCRIPTION
**Pull request by huier23**
Adding tutorial for the first-time user.

### CODE REVIEW

**Review by allen91wu — APPROVED** [review]

**Comment by allen91wu** [comment]
I think the tutorial is looks good to me.
But I think your commit messages should amend.
You need to use commitizen tool[1] to render your commit messages or your CI will be failed.

[1] Please refer the [document](https://github.com/pycontw/mail_handler/blob/master/docs/contributing.md#step-7-work-on-your-new-feature).

**Comment by Lee-W** [comment]
It would be even better if you could move it to `docs/` so that your instruction can be rendered to our static page (https://pycontw.github.io/mail_handler/)

**Review by tai271828 — APPROVED** [review]
Great document improvement!

Nitpicking: It will be great if the commit history could be arranged in a better way. For example:
1. squash two commits into one because they are logically the same feature enhancement.
2. regarding commit message style, you may refer to https://github.com/pycontw/pycon.tw/pull/711#pullrequestreview-376913122

**Comment by tai271828** [comment]
The CI failed for inconsistent commit message style:

```
please enter a commit message in the commitizen format.
commit: Update 2021_mail-handler_user_guide.md

update user guide document
pattern: (build|ci|docs|feat|fix|perf|refactor|style|test|chore|revert|bump)(\(\S+\))?:(\s.*)
Error: Process completed with exit code 14.
```

**Pull request merged**
