### PR TITLE
docs(README): Add render_mail options

### PR DESCRIPTION
**Pull request by allen91wu**
## Types of changes

* **Documentation Update**

## Description

- Add the README about `render_mail` [options]
    - separator ' TEXT ' [default: ]

### CODE REVIEW

**Review by tai271828 — CHANGES_REQUESTED** [review]
@allen91wu  thank you for the contribution. Do you think `disabled by default` easier to read/understand than `[default: ]`?

I know `./render_mail --help` shows something similar to `[default: ]`, and the help description is actually a bad example. Would you mind fixing the description of `click.option separator` at the same time?

**Comment by allen91wu** [comment]
@tai271828 thank you for the suggestion. I fix the README description and also I remove `click.option separator` at the same time. It's a good idea for readability of description document.

**Review by tai271828 — APPROVED** [review]
Looks good to me. I added one small commit to make it more comprehensive. Thanks for the PR!

**Comment by tai271828** [comment]
After CI finishes and passes, I will land the code.

**Pull request merged**
