### PR TITLE
feat(send_mail): add sender name

### PR DESCRIPTION
**Pull request by twtrubiks**

### CODE REVIEW

**Review by Lee-W — COMMENTED** [review]
Thanks for your contribution! But we might need your help to modify the commit message to follow our existing convention. Detail on how to make the CI pass can be found [here](https://pycontw.github.io/mail_handler/contributing/)

**Comment by twtrubiks** [comment]
> Thanks for your contribution! But we might need your help to modify the commit message to follow our existing convention. Detail on how to make the CI pass can be found [here](https://pycontw.github.io/mail_handler/contributing/)

@Lee-W 
Thank you for your reminder.
I did not notice it.
The commit message has been modified.

**Comment by Lee-W** [comment]
@twtrubiks It seems one of the tests fail. Could you please check? Thanks!

**Comment by twtrubiks** [comment]
> @twtrubiks It seems one of the tests fail. Could you please check? Thanks!

Can you please help me take a look?
I don't know why the test has not passed (send mail).

**Review by allen91wu — COMMENTED** [review]
@twtrubiks 
Hi,
I have check the error message of CI.
I think you need to update the test cases [1] to your changes.

[1] https://github.com/pycontw/mail_handler/blob/master/tests/utils.py#L80

**Comment by twtrubiks** [comment]
@allen91wu 
Thank you.   I changed SenderName to Sendername to pass test. 
I actually think it's amazing. Because i don't know the reason.
@Lee-W 
Test should passed. Thank you.

**Comment by Lee-W** [comment]
Thanks @allen91wu for your help. @twtrubiks I just clone it locally and run the checks. I think the only think left is running `inv style.reformat`

**Comment by twtrubiks** [comment]
> Thanks @allen91wu for your help. @twtrubiks I just clone it locally and run the checks. I think the only think left is running `inv style.reformat`

I'm currently processing this command on my local , but he keeps saying that isort can't find the path, let me solve it

**Comment by Lee-W** [comment]
@twtrubiks my best guess is black version, but I'm not quite sure. This is what fixed on my side.

image

**Comment by twtrubiks** [comment]
@Lee-W  Thank you.
github action
black=='19.10b0'
isort=='4.3.21'

my local
black==21.6b0
isort==5.9.1

It's really a version issue.
I have changed them to the same version, and it should pass smoothly this time.

**Pull request merged**
